### ISSUE TITLE
build error AzerothCore rev. 4616d22369df 2019-02-19 23:48:54 +0700 (master branch) 

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-npc-gambler#1]
heres the fix

```diff
diff --git a/src/npc_gambler.cpp b/src/npc_gambler.cpp
index e40b78d..a1c8556 100644
--- a/src/npc_gambler.cpp
+++ b/src/npc_gambler.cpp
@@ -68,7 +68,7 @@ gold. Beware.. He doesn't like cheapskates!
 
 */
 
-#include "config.h"
+#include "Config.h"
 
 class GamblerAnnounce : public PlayerScript
 {

```

**Comment by Winfidonarleyan** [comment]
@milestorme Maybe you'll make a PR?

**Comment by BarbzYHOOL** [comment]
@milestorme open this https://github.com/azerothcore/mod-npc-gambler/blob/master/src/npc_gambler.cpp click on the pencil and edit it then refresh this page https://github.com/azerothcore/mod-npc-gambler/ and open a Pull request 

so now you can submit small fixes easily ! :) and ty for contrib

**Comment by FrancescoBorzi** [comment]
hi @milestorme , thanks for your contribution. Can you please open a PR as suggested above?
