### ISSUE TITLE
Build an error

### ISSUE THREAD

**Issue by yuanf225** [azerothcore/mod-npc-gambler#13]
core：https://github.com/tbcstar/azerothcore-wotlk/commit/7d55071df32575b85002118f9bee4aa83edc6e8b

/home/azerothcore-wotlk/modules/mod-npc-gambler/src/npc_gambler.cpp:408:23: fatal error: no member named 'MonsterWhisper' in 'Creature'
            creature->MonsterWhisper(messageHelp.str().c_str(), player);
            ~~~~~~~~  ^
[ 97%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-services/src/Npc_Services.cpp.o
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:8674: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-gambler/src/npc_gambler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1575: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
root@VM-0-8-ubuntu:/home/azerothcore-wotlk/build#

**Comment by Helias** [comment]
@stoudtlr could you have a look? please :pray:

**Comment by Niceguy1337** [comment]
Please look into this.

**Comment by Helias** [comment]
build fixed, closed by https://github.com/azerothcore/mod-npc-gambler/pull/15
