### ISSUE TITLE
Bug: cant build on ubuntu 22.04

### ISSUE THREAD

**Issue by xengine-qyt** [azerothcore/mod-npc-gambler#21]
### Current Behaviour

![image](https://github.com/user-attachments/assets/c72d084c-35cc-4bb1-a576-53dacfcba787)

### Expected Behaviour

build pass

### Steps to reproduce the problem

make 

### AC rev. hash/commit

last version

### Operating system

ubuntu22.04.4

**Comment by mattburchett** [comment]
I came across this while looking into another bug, and submitted #22 to fix both things, since they were related.
